# permissions for end users to edit bankinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bankinstance-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bank-of-anthos-operator
    app.kubernetes.io/part-of: bank-of-anthos-operator
    app.kubernetes.io/managed-by: kustomize
  name: bankinstance-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - bankinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - bankinstances/status
  verbs:
  - get
